#!/usr/bin/env perl
use Dzpl
    name => 'Config-Identity',
    version => '0.0013',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        File::HomeDir
        File::Spec
        File::Which
        IPC::Open3

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR::Basic' => qr/PruneCruft|GatherDir/ }
{ plugin 'GatherDir' => [ include_dotfiles => 1 ] }

run;
